"""Regenerates Data/Sbi2025.php from the CBS SBI 2025 structure workbook.

Usage: python3 dev/generate-sbi.py sbi2025-structuur-versie-2026-code-zonder-puntjes-nl-en-en.xlsx
Source: https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/activiteiten/standaard-bedrijfsindeling--sbi--
"""
import sys
from pathlib import Path

import openpyxl


def quote(value):
    return "'" + str(value).strip().replace('\\', '\\\\').replace("'", "\\'") + "'"


def main(source):
    sheet = openpyxl.load_workbook(source, read_only=True).worksheets[0]
    lines = [
        '<?php',
        '/**',
        ' * Copyright © Mago Assistant',
        ' */',
        'declare(strict_types=1);',
        '',
        'namespace MagoAssistant\\Kvk\\Data;',
        '',
        '/**',
        ' * SBI 2025 (version 2026), Centraal Bureau voor de Statistiek: code => [NL title, EN title, section].',
        ' * Generated by dev/generate-sbi.py from ' + Path(source).name + '; do not edit by hand.',
        ' */',
        'class Sbi2025',
        '{',
        '    public const TITLES = [',
    ]
    for row in list(sheet.iter_rows(values_only=True))[1:]:
        if row[2]:
            lines.append(f'        {quote(row[2])} => [{quote(row[4])}, {quote(row[5])}, {quote(row[3])}],')
    lines += ['    ];', '}', '']
    target = Path(__file__).resolve().parent.parent / 'Data' / 'Sbi2025.php'
    target.write_text('\n'.join(lines))


if __name__ == '__main__':
    main(sys.argv[1])
